# Generated by Django 5.2.6 on 2025-09-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact_phone', models.TextField()),
                ('services', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('annual_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waiting_period', models.IntegerField()),
                ('copay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_cover.insurancecompany')),
                ('vet_clinic', models.ManyToManyField(related_name='plans', to='pet_cover.vetclinic')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusiveOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('plans', models.ManyToManyField(to='pet_cover.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('plans', models.ManyToManyField(related_name='plans', to='pet_cover.plan')),
            ],
        ),
    ]
