# Generated by Django 5.2.6 on 2025-09-08 23:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_cover', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetclinic',
            name='services',
        ),
        migrations.AlterField(
            model_name='plan',
            name='annual_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='copay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='deductible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='premium',
            field=models.IntegerField(),
        ),
    ]
